version: '3'
services:
  api:
    container_name: pensatta-api
    hostname: pensatta-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - ./:/wd
