version: '3'
services:
  api:
    container_name: pensatta-api
    hostname: pensatta-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - ./:/wd
    depends_on:
      migrations:
        condition: service_completed_successfully
  postgres:
    image: postgres:16.1-bullseye
    container_name: pensatta-postgres
    hostname: pensatta-postgres
    env_file:
      - dev.env
    deploy:
      resources:
        limits:
          cpus: '0.15'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 15s
      timeout: 5s
      retries: 3
  migrations:
    build: 
      dockerfile: migrations.Dockerfile
      context: .
    env_file:
      - dev.env
    depends_on:
      postgres:
        condition: service_healthy
