openapi: "3.0.1"
info:
  version: "1.0.0"
  title: "Pensatta"
  description: "This api handles all pensatta backend logic"

servers:
  - url: http://localhost:3000/api

tags:
  - name: "Register"
    description: "Register a new user"
  - name: "Login"
    description: "Sessions for registered users"
  - name: "Logout"
    description: "Drop current session"
  - name: "Institution"
    description: "Handle all institutions"
paths:
  /register:
    post:
      tags:
        - "Register"
      summary: "Create new user"
      description: "Send a user to create it in our system"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: "object"
                  properties:
                    first_name:
                      type: "string"
                      default: "Daniel"
                    last_name:
                      type: "string"
                      default: "Dorado"
                    list_number:
                      type: "number"
                      default: 123
                    institution_code:
                      type: "string"
                      default: "0101"
                    password:
                      type: "string"
                      default: "test1234"
                    
      responses:
        "201":
          description: "Content created"
          content:
            application/json:
              schema:
                oneOf:
                  - type: "object"
                    properties:
                      username:
                        type: "string"
                        default: "0101160DADO123"
        "400":
          description: "Invalid request"
          content:
            application/json:
              schema:
                oneOf:
                  - type: "object"
                    properties:
                      error:
                        type: "string"
        "500":
          description: "Internal error"
          content:
            application/json:
              schema:
                oneOf:
                  - type: "object"
                    properties:
                      error:
                        type: "string"
  /login:
    get:
      tags:
        - "Login"
      summary: "Get current session, fails if no session found"
      description: "Get current session for a user, fails if no active session found in session storage"
      responses:
        "200":
          description: "Session found"
          content:
            application/json:
              schema:
                oneOf:
                  - type: "object"
                    properties:
                      logged:
                        type: "boolean"
                        default: true
                      user:
                        type: "object"
                        properties:
                          username:
                            type: "string"
                            default: "0101160DADO123"
                          first_name:
                            type: "string"
                            default: "Daniel"
                          last_name:
                            type: "string"
                            default: "Dorado"
                          date_joined:
                            type: "string"
                            default: "2023-04-24T05:43:58.000Z"
                          last_login:
                            type: "string"
                            default: "2024-03-29T19:40:19.234Z"
                          role:
                            type: "string"
                            default: "STUDENT"
                          institution_id:
                            type: "number"
                            default: 1
                          list_number:
                            type: "number"
                            default: 1234
                          language:
                            type: "string"
                            default: "es"
        "401":
          description: "Session not found"
          content:
            application/json:
              schema:
                oneOf:
                  - type: "object"
                    properties:
                      logged:
                        type: "boolean"
                        default: false
                      user:
                        type: "object"
    post:
      tags:
        - "Login"
      summary: "Create a new session in the system for provided username/password"
      description: "Create a new session with username/password"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: "object"
                  properties:
                    username:
                      type: "string"
                      default: "0101160DADO123"
                    password:
                      type: "string"
                      default: "test1234"
      responses:
        "200":
          description: "Session was stablished"
          content:
            application/json:
              schema:
                oneOf:
                  - type: "object"
                    properties:
                      logged:
                        type: "boolean"
                        default: true
                      user:
                        type: "object"
                        properties:
                          username:
                            type: "string"
                            default: "0101160DADO123"
                          first_name:
                            type: "string"
                            default: "Daniel"
                          last_name:
                            type: "string"
                            default: "Dorado"
                          date_joined:
                            type: "string"
                            default: "2023-04-24T05:43:58.000Z"
                          last_login:
                            type: "string"
                            default: "2024-03-29T19:40:19.234Z"
                          role:
                            type: "string"
                            default: "STUDENT"
                          institution_id:
                            type: "number"
                            default: 1
                          list_number:
                            type: "number"
                            default: 1234
                          language:
                            type: "string"
                            default: "es"
        "401":
          description: "Username/Password invalid"
          content:
            application/json:
              schema:
                oneOf:
                  - type: "object"
                    properties:
                      logged:
                        type: "boolean"
                        default: false
                      user:
                        type: "object"
  /logout:
    delete:
      tags:
        - "Logout"
      summary: "Drops current session in the system"
      description: "Drops current session"
      responses:
        "200":
          description: "Session was deleted"
  
  /institution:
    get:
      tags:
        - "Institution"
      summary: "Gets all institutions"
      description: "Get all institutions registered in system"
      responses:
        "200":
          description: "Institutions was retrieved"
          content:
            application/json:
              schema:
                oneOf:
                  - type: "object"
                    properties:
                      institutions:
                        type: "array"
                        items:
                          type: "object"
                          properties:
                            name:
                              type: "string"
                              default: "Institution Name"
                            email:
                              type: "string"
                              default: "institution@email.com"
                            country:
                              type: "string"
                              default: "colombia"
                            province:
                              type: "string"
                              default: "bogota"
                            city:
                              type: "string"
                              default: "bogota"
                            code:
                              type: "string"
                              default: "0101"
                            language:
                              type: "string"
                              default: "es"
        "500":
          description: "Internal error"
          content:
            application/json:
              schema:
                oneOf:
                  - type: "object"
                    properties:
                      error:
                        type: "string"
    post:
      tags:
        - "Institution"
      summary: "Creates new institution"
      description: "Creates a new institution with provided info"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: "object"
                  properties:
                    name:
                      type: "string"
                      default: "Institution Name"
                    email:
                      type: "string"
                      default: "institution@email.com"
                    country:
                      type: "string"
                      default: "colombia"
                    province:
                      type: "string"
                      default: "bogota"
                    city:
                      type: "string"
                      default: "bogota"
                    code:
                      type: "string"
                      default: "0101"
                    language:
                      type: "string"
                      default: "es"
      responses:
        "201":
          description: "Institution created successfully"
          content:
            application/json:
              schema:
                oneOf:
                  - type: "object"
                    properties:
                      created:
                        type: "boolean"
                        default: "true"
        "500":
          description: "Internal error"
          content:
            application/json:
              schema:
                oneOf:
                  - type: "object"
                    properties:
                      error:
                        type: "string"
